### PR TITLE
bcm27xx/bcm2712: add rp1 kmods

### PR DESCRIPTION
**Pull request by graysky2**
Attempt to add the following config options:
CONFIG_SENSORS_RP1_ADC=y
CONFIG_MFD_RP1=y
CONFIG_COMMON_CLK_RP1=y
CONFIG_PWM_RP1=y

And corresponding modules:
rp1
rp1_adc
rp1_pio

### CODE REVIEW

**Comment by graysky2** [comment]
@namiltd - Can you take a look at this? It builds but I do not see the modules I am expecting in `/lib/modules/6.12.4`

**Comment by namiltd** [comment]
Is it ok for kernel 6.6.x?

**Comment by graysky2** [comment]
Have not tested for 6.6.x currently building for 6.12.4.  Should also mention that I have no idea if I am adding these to the right files/I have never added modules before :grin:

**Comment by namiltd** [comment]
If KernelPackage/rp1 is hidden, then some other package should have it in DEPENDS.

**Comment by graysky2** [comment]
I removed the `HIDDEN=1` but still no modules are in the image

**Comment by namiltd** [comment]
Do you want to enable each of these modules independently? And there are no depends between them?

**Comment by graysky2** [comment]
All of them should be loaded if the device is RPi5B.  It would be more simple if there was one file to enable them.

**Comment by namiltd** [comment]
The file 950-0550-hwmon-Add-RP1-ADC-and-temperature-driver.patch already contains these definitions.

**Comment by graysky2** [comment]
So that patch is adding support in the kernel but we still have to package the module which is what I do not know how to do

**Comment by namiltd** [comment]
SENSORS_RP1_ADC depends on MFD_RP1
MFD_RP1 depends on MFD_CORE
PWM_RP1 depends on ARCH_BCM2835 || COMPILE_TEST
COMMON_CLK_RP1	depends on PCI || COMPILE_TEST and depends on COMMON_CLK

So you need to add the appropriate settings to KCONFIG (or DEPENDS)

**Comment by graysky2** [comment]
Where can I specify `.config` options to pass for the RPi5B subtarget?  For example, these need to be built as modules so their .ko can be packaged.

```
            CONFIG_FIRMWARE_RP1
            CONFIG_RP1_PIO
            CONFIG_PINCTRL_RP1
            CONFIG_COMMON_CLK_RP1_SDIO
            CONFIG_MBOX_RP1
            CONFIG_PWM_PIO_RP1
```

**Comment by graysky2** [comment]
Why isn't https://github.com/graysky2/openwrt/commit/6552cc7f5f384ed9e15d748d9b74676ebc278b70 allowing those modules to be build?

```
% find build_dir/target-aarch64_cortex-a76_musl -name '*rp1*.ko'
%
```

**Comment by namiltd** [comment]
Most likely the dependencies are not met. Try compiling with CONFIG_ALL_KMODS=y.

**Comment by graysky2** [comment]
OK, the latest commit builds them and I am able to use them when I boot into the image.
```
% find build_dir/target-aarch64_cortex-a76_musl -name '*rp1*.ko'
build_dir/target-aarch64_cortex-a76_musl/linux-bcm27xx_bcm2712/linux-6.12.4/drivers/firmware/rp1.ko
build_dir/target-aarch64_cortex-a76_musl/linux-bcm27xx_bcm2712/linux-6.12.4/drivers/mailbox/rp1-mailbox.ko
build_dir/target-aarch64_cortex-a76_musl/linux-bcm27xx_bcm2712/linux-6.12.4/drivers/misc/rp1-pio.ko
build_dir/target-aarch64_cortex-a76_musl/linux-bcm27xx_bcm2712/linux-6.12.4/drivers/pwm/pwm-pio-rp1.ko
```
```
# lsmod|grep rp1
rp1                    12288  1 rp1_pio
rp1_mailbox            12288  1 
rp1_pio                24576  0 
```

My next question is how should they be integrated into the various files within `package/kernel/linux/modules/*.mk`

**Comment by graysky2** [comment]
https://github.com/openwrt/openwrt/pull/17233 please continue any discussion there

**Pull request closed without merging**
